### ISSUE TITLE
Consider relationship to marketing-oriented "explainers"

### ISSUE THREAD

**Issue by aturon** [rust-lang-nursery/edition-guide#1]
We're going to want to create very brief explainers about the epoch concept and the various features in Rust 2018. It's not yet clear how we'll want to organize those, but it's obviously related to this guide!

cc @ashleygwilliams @jonathandturner

**Comment by steveklabnik** [comment]
I did this in https://github.com/rust-lang-nursery/edition-guide/commit/8bb94db1ef7b61689c88b66d35e7237f8d9ba382
