### ISSUE TITLE
How to create a *new* project that uses the 2018 edition?

### ISSUE THREAD

**Issue by japaric** [rust-lang-nursery/edition-guide#102]
The guide has a great section on migrating an existing crate to the 2018 edition but if you want to start a new project that uses the 2018 edition is not obvious that you need to set `package.edition = "2018"` in your Cargo.toml as this is only mentioned (AFAICT) in Section 1.1 Transitioning your code to a new edition.

It would be great to have a short section on this topic.

**Comment by steveklabnik** [comment]
Once the edition stabilizes, this will be added for you, so we didn't really focus on it as it will be pretty much a moot point in the near future.

**Comment by japaric** [comment]
It's the plan to have RC1 Cargo generate 2018 projects by default? If not then *not* having documentation on this doesn't seem like the best way to encourage people to try out the 2018 edition during the next 12 weeks, IMO.

**Comment by alexcrichton** [comment]
Huh... interesting! I don't think we've really talked much about this at all, but I think we'll want to switch the default during the testing period when everything else is stable as well. To that end once `#![feature(rust_2018_preview)]` stabilizes we should likely change Cargo's default

**Comment by Mark-Simulacrum** [comment]
It is my expectation that `#![feature(rust_2018_preview)]` should be stabilized in RC1 beta.

**Comment by ehuss** [comment]
FWIW, the default for `cargo new` is now 2018 as of rust-lang/cargo#5989.

**Comment by steveklabnik** [comment]
I still think this is fine to say explicitly, so let's say it!
