### ISSUE TITLE
Document that `extern crate test` is still required for benchmarks with 2018 edition

### ISSUE THREAD

**Issue by dekellum** [rust-lang-nursery/edition-guide#121]
Originally reported in rust-lang/rust#55133, and of late it seems I'm not the only one surprised by the continued need to use `extern crate test` in each benchmark as a special case (and with `edition="2018"`)

Currently the guide's _Path clarity_ section doesn't seem to indicate there are any exceptions:

https://rust-lang-nursery.github.io/edition-guide/rust-2018/module-system/path-clarity.html
> Here's a brief summary:
> * `extern crate` is no longer needed

Wouldn't it be helpful to add this or other exceptional cases as a footnote or under the _More details: No more `extern crate`_ section, with some rationale as indicated in rust-lang/rust#55133? My attempt at a user-centric elaboration:

> `#![feature(test)]` is unstable and doesn't by itself import the `test` pseudo-crate for benchmarks.

Cc @Mark-Simulacrum (not sure if you also disagree with _documenting_ this discrepancy)

**Comment by steveklabnik** [comment]
this isn't specific to test, it's for any of the crates in the sysroot, like `proc_macro`

**Comment by dekellum** [comment]
That sounds like a much better explanation, thanks.
