### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by gurry** [rust-lang-nursery/edition-guide#126]
The link "improved error messages" on [this page](https://rust-lang-nursery.github.io/edition-guide/rust-2018/the-compiler/index.html) is broken. The problem is due the underlying URL being this:

`https://rust-lang-nursery.github.io/edition-guide/rust-2018/the-compiler/rust-2018/the-compiler/improved-error-messages.html`

instead of this:
`https://rust-lang-nursery.github.io/edition-guide/rust-2018/the-compiler/index.html`

**Comment by xonatius** [comment]
Same for other pages, for example [Module system](https://rust-lang-nursery.github.io/edition-guide/rust-2018/module-system/index.html). Looks like links from 419edb885ec1a98c0747b3907003d79e3e6b93a9  need to be fixed.

**Comment by ehuss** [comment]
Links should now be fixed as of #152.
