### ISSUE TITLE
Published version is out of date?

### ISSUE THREAD

**Issue by jdm** [rust-lang-nursery/edition-guide#135]
I looked at https://rust-lang-nursery.github.io/edition-guide/rust-2018/error-handling-and-panics/aborting-on-panic.html and saw a typo which I went to correct. It turns out it was corrected in early December 2018; what does it take to update the published version?

**Comment by dwijnand** [comment]
Due to the travis-ci.com move: https://github.com/rust-lang-nursery/edition-guide/pull/130#issuecomment-454567141 All good now!
