### ISSUE TITLE
All links broken on https://rust-lang-nursery.github.io/edition-guide/rust-2018/edition-changes.html

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/edition-guide#138]
Every link here takes me to 404 - it creates URLS containing incorrect "rust-2018/rust-2018" paths.

This looks pretty bad and it's hopefully an easy fix.

**Comment by steveklabnik** [comment]
This shouldn’t be published to github pages anymore. It lives under doc.rust-Lang.org these days

**Comment by brson** [comment]
In addition to ceasing publication on github.io the description of the repo needs to change and the README.

**Comment by siddharthasahu** [comment]
They are also not the same versions. Eg. https://rust-lang-nursery.github.io/edition-guide/rust-2018/edition-changes.html does not exist on the stable version.

cc #76

**Comment by dwijnand** [comment]
How and when is this guide published to https://doc.rust-lang.org/ ?

**Comment by steveklabnik** [comment]
@dwijnand every rust release, we update the submodule, and so it should be updated like any other docs; changes from here will take between 7 and 13 weeks to make it to the main doc.rust-lang.org page.

**Comment by dwijnand** [comment]
I realise your time is limited, but wouldn't it be better if https://doc.rust-lang.org/edition-guide/ were a redirect to (or proxy of) https://rust-lang-nursery.github.io/edition-guide/, with the latest and greatest fixes that have landed?  The offline rust distributions will have some slightly older/stale version and, if need be, https://doc.rust-lang.org/stable/edition-guide can host that version of the guide, no?

**Comment by steveklabnik** [comment]
Sure, that’s why this bug is open.

**Comment by steveklabnik** [comment]
Err sorry, no. I mean, in some sense, it would be good, but it’s not how we distribute our docs. This isn’t possible with today’s setup.

There are also advantages to that setup; we don’t want everyone to point to the latest and greatest, as it may have stabilized in nightly but not yet hit stable.

(This bug is about redirects the other way.)

**Comment by ehuss** [comment]
Links are now fixed as of #152, and a redirect has been established with #150.  The doc.rust-lang.org website should update once rust-lang/rust#58800 is merged and a new nightly is published.
