### ISSUE TITLE
Seemingly incorrect info about path clarity

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/edition-guide#139]
In "2018-specific changes":

- "use declarations must begin with ... an external crate name"

This does not seem to be true - paths like "use foo::bar" will resolve a "foo" in local scope, not just a crate name.

- "to catch possible ambiguities with uniform paths (which is planned for inclusion soon #55618)."

That issue is closed and presumably in stable?

In "Path clarity":

- "Absolute paths begin with a crate name, where the keyword crate refers to the current crate."

It's not clear what "absolute paths" means. Is this for "::"? It should be explicit.

Again on this page I don't see mention of unprefixed paths resolving names in local scope, which they do.

- "In Rust 2018, paths in use declarations must begin with a crate name, crate, self, or super"

Again, 'use' declarations seem to resolve names in local scope. No mention of "::" here.

All of the above applies with or with out the 'uniform_paths' feature.

**Comment by Centril** [comment]
> This does not seem to be true - paths like "use foo::bar" will resolve a "foo" in local scope, not just a crate name.

Yes; this is outdated; in 1.32 uniform paths were stabilized.

> That issue is closed and presumably in stable?

Correct.

> It's not clear what "absolute paths" means. Is this for "::"? It should be explicit.

Correct and agreed.

**Comment by brson** [comment]
Thanks @Centril.

Since uniform paths are stable there's quite a bit more to be updated there too.

**Comment by Centril** [comment]
Thanks for reminding us @brson. :)

Would you perhaps be willing to go over the guide and update where needed?

**Comment by brson** [comment]
@Centril I'm willing but I don't know if I'll be able to find the time soon. I'll put it on my todo list though. Maybe this weekend, but no guarantees.

**Comment by ehuss** [comment]
Sorry, I've been trying to figure out how to document uniform paths over the past week, but I haven't felt like I understand it well enough to document it clearly and correctly.  I was intending to see what it would take to update the reference before trying to update the summary here, but maybe doing it the other way around would be better.   This is also still [in flux](https://github.com/rust-lang/rust/pull/57745) so I didn't want to put too much effort if it is going to change in a few days.

**Comment by petrochenkov** [comment]
@ehuss 
I don't think https://github.com/rust-lang/rust/pull/57745 is blocking documentation for uniform paths specifically (it doesn't change anything on pure 2018 edition).
