### ISSUE TITLE
Include version references on shipped features?

### ISSUE THREAD

**Issue by dwijnand** [rust-lang-nursery/edition-guide#16]
Some of the changes described in guide are already stable and available in current Rust without having to opt-in, such as default match bindings, and `?` support in main and tests.

So I was thinking: should these changes (or perhaps all changes described) mention the version as of which they're available?

**Comment by Centril** [comment]
I would say no; it would clutter things.

**Comment by dwijnand** [comment]
I'm happy to explore minimally-cluttering solutions to this proposal. 😄

The use case I had in mind is someone without the bandwidth to follow all the changes in every 6-week release but does have the time to read the edition guide might benefit from knowing that so-and-so change is already available as of X.Y rust version.

**Comment by Centril** [comment]
> I'm happy to explore minimally-cluttering solutions to this proposal. 😄

Go for it :) 🎉

**Comment by dwijnand** [comment]
I present myself as one such user. I happen to know that default match bindings and `?` in main/tests are readily available in 1.26, and I wonder: are some of the others too?

**Comment by dwijnand** [comment]
As such, I'd need help back-filling the info. 😁

**Comment by Centril** [comment]
For lots (or too much...) of detail consult [the lang tab on the project management spreadsheet](https://docs.google.com/spreadsheets/d/188xuIgrzGLCu68UKpRjcmpRZ0ytxe-HG_ClViBqFvbI/edit#gid=1916240332) :)

I think at least `'_` landed on 1.26 and `dyn Trait` lands on 1.27.

**Comment by dwijnand** [comment]
OK. I'll start with those, and if the change lands the rest can be backfilled later.

Thanks @Centril.
