### ISSUE TITLE
Tracking issue for NLL in Rust 2015

### ISSUE THREAD

**Issue by carols10cents** [rust-lang-nursery/edition-guide#166]
When NLL is enabled in Rust 2015, this part of the edition guide should get updated:

https://github.com/rust-lang-nursery/edition-guide/blame/5f3cc2a5618700efcde3bc00799744f21fa9ad2e/src/rust-2018/edition-changes.md#L6

I think this is the issue for NLL in 2015? https://github.com/rust-lang/rust/issues/57895

This is the full NLL tracking issue: https://github.com/rust-lang/rust/issues/43234

**Comment by Centril** [comment]
@carols10cents  That part has already changed on master.

**Comment by carols10cents** [comment]
oooops, idk how i got on a commit instead of master in the github ui. thanks!
