### ISSUE TITLE
Suggest/Talk about --all-targets and feature gating

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang-nursery/edition-guide#19]
See https://github.com/rust-lang/rust/issues/51208#issuecomment-395573875; copying:

So `--all-targets` seems to work great. Feature handling is harder, but since rustfix supports incremental migration that's fine, for crates with non-mutually exclusive features, `cargo +nightly fix --prepare-for 2018 -- --all-targets --no-default-features` and `cargo +nightly fix --prepare-for 2018 --allow-dirty -- --all-targets --all-features` should be sufficient to migrate.

If exclusive features are present users need to run with `--feature blah` and then `--features baz`. For the alpha release that seems sufficient; we might want rustfix to automatically do this with some flag, but I don't think that's very feasible due to exclusionary feature groups.

We should update the migration docs.

**Comment by Mark-Simulacrum** [comment]
@nikomatsakis [suggested](https://github.com/rust-lang/rust/issues/51208#issuecomment-395609671) that we also ask users to provide feedback about the feature patterns beyond all/none that they use.

**Comment by alexcrichton** [comment]
One question that I think would be worth considering is whether to enable this sort of behavior by default as well, as 

```
cargo +nightly fix --prepare-for 2018 --allow-dirty -- --all-targets --all-features 
```

is pretty wordy!

**Comment by Mark-Simulacrum** [comment]
`--all-features` is also not technically enough, as you might have features which enable/disable functionality when enabled/disabled, e.g. something like a `std` feature which is on by default but when disabled you'll see alloc or core imports, for example

**Comment by Centril** [comment]
Closing since #70 rendered this moot.
