### ISSUE TITLE
async/await listed as both available and not available:

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang-nursery/edition-guide#29]
We have the text "For example, async/await is available in Rust 2018, but not Rust 2015." in https://rust-lang-nursery.github.io/edition-guide/editions/transitioning.html#prepare-for-the-next-edition

But the Feature Status (https://rust-lang-nursery.github.io/edition-guide/2018/status.html) shows it as not yet available

**Comment by Centril** [comment]
Should probably say "will be available in Rust 2018.." ?
