### ISSUE TITLE
Standardize on old way then new way or vice versa

### ISSUE THREAD

**Issue by Hello71** [rust-lang-nursery/edition-guide#32]
For example, in `2018/transitioning/traits/impl-trait.md`, it switches between first `impl Trait` then `T: Trait` to the other way around. I didn't read the sentence right after the code block, so I was confused about which is former and which is latter.

It would probably be good to decide on one way or the other. I think old way then new way is a better general rule than the other way around. (of course being free to change the order if it reads better.)

**Comment by Centril** [comment]
Old then new consistently sounds good.

Happy to accept a patch that fixes this :)
