### ISSUE TITLE
Mobile styles are messed up

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [rust-lang-nursery/edition-guide#36]
### To reproduce

Open https://rust-lang-nursery.github.io/edition-guide/introduction.html in a mobile browser like Android Chrome or Firefox Mobile.

### Expected

Well-formatted page with discoverable navigation.

### Actual

* The title is truncated.
* There is no sign that the outline is there. 
* The gesture to open the outline (swipe ~~left~~ right) does not work reliably. I was unable to determine the exact conditions when it works and when it fails though, feels random.

![screenshot_20180623-144531](https://user-images.githubusercontent.com/302938/41809337-a5b1beda-76f4-11e8-889b-006f6db29585.png)

------

Tried it in Fixefox Android 60.0.2 and Android Chrome 67.0.3396.87.

**Comment by ExpHP** [comment]
I had to find this issue to even figure out how to get past the first page.  It is surprising how different this is from all other mdbook sites.

**Comment by steveklabnik** [comment]
This should be fixed now; please let me know if it isn't!
