### ISSUE TITLE
"Lifetime elision in impl" inconsistency

### ISSUE THREAD

**Issue by Lehona** [rust-lang-nursery/edition-guide#42]
The 2015 example: 
`impl<'a, 'b> SomeTrait<'a> for SomeType<'a, 'b> { ... }`

The 2018 example:
`impl SomeTrait<'tcx, 'gcx> for SomeType<'tcx, 'gcx> { ... }`
but I think it should be:
`impl SomeTrait<'tcx> for SomeType<'tcx, 'gcx> { ... }`

(SomeTrait is only generic over one lifetime, not two)

**Comment by Arnavion** [comment]
Fix is in #57
