### ISSUE TITLE
impl Trait in argument position are universals

### ISSUE THREAD

**Issue by Centril** [rust-lang-nursery/edition-guide#5]
> The above is all you need to know to get going with `impl Trait`, but for
some more nitty-gritty details: type parameters are universals, `impl Trait`
are existentials. Okay, maybe that's a bit too jargon-heavy. Let's step back.

https://github.com/rust-lang-nursery/edition-guide/blob/master/src/2018/transitioning/traits/impl-trait.md#more-details

This paragraph could be a bit confusing, as `arg: impl Trait` constitutes universal quantification.

**Comment by steveklabnik** [comment]
👍
