### ISSUE TITLE
Talk loudly about not splitting the ecosystem

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang-nursery/edition-guide#54]
Right now the compatibility section is fairly small and isolated -- we should perhaps split this out or emphasize it more. People are concerned about ecosystem splits, which AFAIK are (impossible).

**Comment by Centril** [comment]
Does https://github.com/rust-lang-nursery/edition-guide/pull/52 fix this?

**Comment by Mark-Simulacrum** [comment]
I think so, yes.

**Comment by steveklabnik** [comment]
Since #52 fixed this, gonna close!
