### ISSUE TITLE
Update to reflect module system as-is

### ISSUE THREAD

**Issue by Centril** [rust-lang-nursery/edition-guide#62]
Once the module system changes as specified in https://internals.rust-lang.org/t/relative-paths-in-rust-2018/7883 is done, update guide.

**Comment by steveklabnik** [comment]
My understanding is that they'll be two different options? @aturon can you add any context here?

**Comment by Centril** [comment]
What I mean is: Whenever one of the options is chosen over the other we should update the guide.

**Comment by joshtriplett** [comment]
https://github.com/rust-lang-nursery/edition-guide/pull/74

**Comment by steveklabnik** [comment]
Has an option been chosen?

**Comment by steveklabnik** [comment]
It appears like this didn't merge yet https://github.com/rust-lang/rust/issues/53130#issuecomment-421819199

which means it's not in the RC :/

**Comment by steveklabnik** [comment]
From @eddyb :

```text
you can't have two variants of a system with feature-gates
so "anchored use paths" is the default on Rust 2018, and has been for a while
only uniform paths require a feature gate and will most likely be a thing later on in 2019 or never shrug
I don't even know what we FCP'd
oh we FCP'd the thing that landed like a week ago
```
