### ISSUE TITLE
Document how to transition imports of procedural macros

### ISSUE THREAD

**Issue by vks** [rust-lang-nursery/edition-guide#66]
It is not clear how code importing procedural macros using `extern crate` should be updated. A typical example:

```rust
#[macro_use] extern crate serde_derive;

#[derive(Serialize, Deserialize)]
...
```

How should `#[macro_use] extern crate` be replaced so that `#[derive(...)]` still works?

**Comment by vks** [comment]
This works:
```rust
use serde_derive::{Serialize, Deserialize};

#[derive(Serialize, Deserialize)]
...
```

**Comment by eminence** [comment]
hi @vks, this seems to be covered in the "Macro changes" section of the guide: https://rust-lang-nursery.github.io/edition-guide/2018/transitioning/modules/macros.html

Was there anything in particular about this section that was confusing, or that you think could be improved?  I guess one of the problems is that in Rust 2015, you didn't have to explicitly name the macro (or derive) you want to use, but in Rust 2018 you have to name them.

**Comment by vks** [comment]
It was not clear to me you should import the trait you want to derive. If
you look at the the docs, there is no macro called `Serialize` , only one
called `derive_Serialize`. Importing it does not work.

The transition guide states you have to name the macro, which seems
inaccurate in this case. It should mention that in the case of procedural
macros, you have to mention the trait you want to derive.

**Comment by petrochenkov** [comment]
@vks 
>The transition guide states you have to name the macro, which seems
inaccurate in this case. It should mention that in the case of procedural
macros, you have to mention the trait you want to derive.

`Serialize` *is* a macro with the same name as a trait.
The docs mentioning `derive_Serialize` are wrong in this case, `derive_Serialize` is some naming scheme used only for unstable legacy syntax extensions, it doesn't apply to stable "modern" proc macros.

**Comment by vks** [comment]
@petrochenkov 
> Serialize is a macro with the same name as a trait.

I think this is not something that users of procedural users necessarily know. That it is not mentioned in the docs does not help.
