### ISSUE TITLE
Move the edition guide to a more prominent location

### ISSUE THREAD

**Issue by Centril** [rust-lang-nursery/edition-guide#76]
We should eventually move the guide out of the https://rust-lang-nursery.github.io/ URL and give it a more official-looking, short and sweet URL instead.

We decided that we will punt on this for Preview 2; but we should do this for Release Candidate 1.

A suggested URL for the whole edition is https://rust-lang.org/edition/ and https://rust-lang.org/edition/2018/  then goes to the 2018 page.

We can also move it to  https://docs.rust-lang.org/edition/

**Comment by orium** [comment]
Note that when this is done some urls in cargo will need to be updated.  At the time of this comment there are two references to `rust-lang-nursery.github.io`:

```text
orium@laptop-orion cargo % rp rust-lang-nursery.github.io
src/cargo/util/diagnostic_server.rs
174:  https://rust-lang-nursery.github.io/edition-guide/editions/transitioning-your-code-to-a-new-edition.html
196:  https://rust-lang-nursery.github.io/edition-guide/editions/transitioning-your-code-to-a-new-edition.html
```

**Comment by steveklabnik** [comment]
This is not happening as part of the release candidate, so de-milestoning.

**Comment by tmandry** [comment]
Will this happen before release? It looks like there was some mention on Discord, but no formal decision made.

At least one rustc PR (https://github.com/rust-lang/rust/pull/55185) includes a guide URL; we're not sure if it's going to change.

**Comment by dwijnand** [comment]
https://doc.rust-lang.org/stable/edition-guide/ is now a thing, but note that it's some other version of the guide that isn't https://rust-lang-nursery.github.io/edition-guide/.

Note the "Minimum Rust Version" in:
* https://doc.rust-lang.org/stable/edition-guide/rust-2018/ownership-and-lifetimes/non-lexical-lifetimes.html, vs
* https://rust-lang-nursery.github.io/edition-guide/rust-2018/ownership-and-lifetimes/non-lexical-lifetimes.html

**Comment by dwijnand** [comment]
Interestingly hasn't changed with the 1.32 release.

**Comment by siddharthasahu** [comment]
I think the minimum versions needs an update at https://doc.rust-lang.org/stable/edition-guide/rust-2018/documentation/new-editions-of-the-book.html

**Comment by ehuss** [comment]
The guide now lives at https://doc.rust-lang.org/edition-guide/.  The latest version will be published at https://doc.rust-lang.org/nightly/edition-guide/, and should be live soon.

@siddharthasahu I updated the minimum version for that page in #149. I'm not sure if that's the change you were thinking of, feel free to leave comments on that PR.
