### ISSUE TITLE
Should fix unit tests by default as well

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/edition-guide#8]
Currently I think the suggestion is to run `cargo fix` but this currently means that unit tests, benchmarks, etc, will not be fixed. This can be a poor experience where you fix your way into the 2018 edition only to hit a roadblock when you execute `cargo test`.

I see one of two possibilities here:

* First up we could change `cargo fix` to automatically fix all Cargo targets by default. I like this in that it's sort of what I think we want, but I also don't like this in that it's *still* not guaranteed to fix everything. We'd need to encourage users to also do things like `cargo fix -- --all-targets --all-features` (in today's sytnax)
* We could alternatively add documentation to the edition guide suggesting that before enabling `edition = '2018'` you should attempt to fix all targets. This would involve both the `--all-targets` flag (perhaps) as well as things like `--feature foo` for the specific local crate.

I'm personally leaning towards the latter, but I'm curious what others think!

cc @killercup

**Comment by alexcrichton** [comment]
Hm bah but currently you *also* have to write `#![feature(rust_2018_preview)]` everywhere which is a bummer...

**Comment by Mark-Simulacrum** [comment]
Closing as duplicate of https://github.com/rust-lang-nursery/edition-guide/issues/19.
