### ISSUE TITLE
Text for 3.49 "Lifetime elision in impl" is actually about in-band lifetimes

### ISSUE THREAD

**Issue by scottmcm** [rust-lang-nursery/edition-guide#84]
This one should be about things like

```rust
impl<I:MyIterator> MyIterator for &mut I {
```
```rust
impl<T> Drop for SetOnDrop<'_, T> {
```

Is it possible the wrong text got copied over in the refactor?

Full demo, in case it's helpful: https://play.rust-lang.org/?gist=f307a4f4f2a808c3eba9da6ff6bee55f&version=nightly&edition=2018

**Comment by steveklabnik** [comment]
It's possible, but I'm more interested in fixing it than figuring out why it's wrong :)
