### ISSUE TITLE
Include a page about 2018-only changes

### ISSUE THREAD

**Issue by Centril** [rust-lang-nursery/edition-guide#91]
Include a dedicated page that explains exactly what parts that are only available on 2018 + all the breakage.
This should be a tiny list.

**Comment by steveklabnik** [comment]
This has to land tonight, RC1 is shipping in the morning.

**Comment by Centril** [comment]
@steveklabnik I'll get to working on it today; was very much asleep when you wrote your comment =P

**Comment by steveklabnik** [comment]
This did not land, de-milestoning.

**Comment by siddharthasahu** [comment]
Is it still scheduled? This page would be really helpful.

**Comment by ehuss** [comment]
If I wrote a page for this, would you consider adding it? AFAIK, here is an exhaustive list of the stable 2018-specific changes:

- `dyn` is now a full keyword.
- `async`, `await`, `try` are now reserved keywords.
- Added `?` kleene operator to macros-by-example.
- NLL
- tyvar_behind_raw_pointer is now a hard error.
- Overflowing literals are now rejected.
- Anonymous trait function parameters are not allowed.
    - All irrefutable patterns are allowed with a body.
- Paths:
    - Paths starting with `::` can only reference crates.
    - `use` declarations can reference crates in the extern prelude.
    - `use` declarations cannot reference the crate root.
        - `::` leading prefix required for name clashes (uniform_paths future-proofing).
    - Visibility paths must be absolute.

Additionally, I think it wouldn't hurt to include the 2018 idioms:

- bare_trait_objects: `dyn Trait` is recommended over `Trait`
- unused_extern_crates: `extern crate` should not be used
- ellipsis_inclusive_range_patterns: `...` ranges are deprecated, should use `..=`
- elided_lifetimes_in_paths: Lifetimes should not be elided in some cases.
- explicit_outlives_requirements: Lifetime bounds should be elided in some cases.

**Comment by Centril** [comment]
@ehuss Yeah I was supposed to fix it but never got the time; if you can do it, that'd be great.

**Comment by steveklabnik** [comment]
> Additionally, I think it wouldn't hurt to include the 2018 idioms:

The release team has been very not interested in describing the idiom
lints, as they're not ready yet. I would leave this out.
